remote_theme: zendesk/jekyll-theme-zendesk-garden

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links

title: Tuakiri Documentation TEST

owner_name: Tuakiri
owner_url: https://tuakiri.ac.nz/

version: false

sidebar:
  - label: Tuakiri Core Documents
    children:
      - test
  - label: Identity Providers
    children:
      - idp_3x_inst
  - label: eduGAIN resources
    children:
      - eduGAIN Information Pack
      - edugain_info_pack
