remote_theme: zendesk/jekyll-theme-zendesk-garden@v0.7.3

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links

title: Tuakiri Documentation TEST

owner_name: Tuakiri
owner_url: https://tuakiri.ac.nz/

version: false

sidebar:
  - label: Tuakiri Core Documents
    children:
      - test
  - label: Identity Providers
    children:
      - identity_providers/installing_a_shibboleth_3_x_idp
  - label: eduGAIN resources
    children:
      - edugain_resources/edugain_information_pack
